"""Pure domain models, enums, and policies."""

from ytdlp_bot.domain.commands import (
    AcceptedJob,
    AdminView,
    CancelArgs,
    CommandRequest,
    CommandResult,
    HelpArgs,
    HelpView,
    StatusArgs,
    StatusView,
    UserError,
    YtdlArgs,
    Ytmp3Args,
    build_command_arguments,
    parse_text_command,
)
from ytdlp_bot.domain.enums import (
    AccessMode,
    ArtifactAccessState,
    AudioBitrate,
    CommandName,
    FailureCode,
    JobState,
    MediaMode,
    Platform,
    UploadOutcome,
    VideoQuality,
    WarningCode,
    WorkerPhase,
)
from ytdlp_bot.domain.errors import DomainError, DomainFailure, failure
from ytdlp_bot.domain.identity import (
    ArtifactId,
    Identity,
    JobId,
    MessageContext,
    MessageReference,
)
from ytdlp_bot.domain.jobs import Artifact, DownloadRequest, Job, PlaylistEntry
from ytdlp_bot.domain.progress import DeliveryPlanDecision, ProgressSnapshot
from ytdlp_bot.domain.state_machine import (
    apply_artifact_transition,
    apply_job_transition,
    apply_playlist_entry_transition,
)

__all__ = [
    "AcceptedJob",
    "AccessMode",
    "AdminView",
    "Artifact",
    "ArtifactAccessState",
    "ArtifactId",
    "AudioBitrate",
    "CancelArgs",
    "CommandName",
    "CommandRequest",
    "CommandResult",
    "DeliveryPlanDecision",
    "DomainError",
    "DomainFailure",
    "DownloadRequest",
    "FailureCode",
    "HelpArgs",
    "HelpView",
    "Identity",
    "Job",
    "JobId",
    "JobState",
    "MediaMode",
    "MessageContext",
    "MessageReference",
    "Platform",
    "PlaylistEntry",
    "ProgressSnapshot",
    "StatusArgs",
    "StatusView",
    "UploadOutcome",
    "UserError",
    "VideoQuality",
    "WarningCode",
    "WorkerPhase",
    "YtdlArgs",
    "Ytmp3Args",
    "apply_artifact_transition",
    "apply_job_transition",
    "apply_playlist_entry_transition",
    "build_command_arguments",
    "failure",
    "parse_text_command",
]
